code/the_right_way/delegation/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('special-offers/<slug:slug>/', views.special_offer_detail, name='special_offer_detail'),
    path('products/', views.product_list, name='product_list'),
]

app_name = 'delegation'

code/the_right_way/detail_view/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('products/<slug:slug>/', views.product_detail, name='product_detail'),
]

app_name = 'detail_view'

code/the_right_way/list_view/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('products-unpaged/', views.product_list_unpaged, name='product_list_unpaged'),
    path('products/', views.product_list, name='product_list'),
    path('products-refactored/', views.product_list_refactored, name='product_list_refactored'),
]

app_name = 'list_view'

code/the_right_way/the_pattern/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('example/<str:arg>/', views.example_view, name='example_name'),
]

app_name = 'the_pattern'

code/the_right_way/urls.py
# For more information please see:
#     https://docs.djangoproject.com/en/stable/topics/http/urls/
from django.contrib import admin
from django.urls import include, path

from . import views

urlpatterns = [
    path('', views.index),
    path('view-source/<str:namespace>/', views.view_source, name='view_source'),
    path('admin/', admin.site.urls),
    path('the-pattern/', include('the_right_way.the_pattern.urls')),
    path('the-pattern-explanation/', include('the_right_way.the_pattern.explanation_urls')),
    path('context-data/', include('the_right_way.context_data.urls')),
    path('context-data-discussion/', include('the_right_way.context_data.discussion_urls')),
    path('common-context-data/', include('the_right_way.common_context_data.urls')),
    path('common-context-data-discussion/', include('the_right_way.common_context_data.discussion_urls')),
    path('url-parameters/', include('the_right_way.url_parameters.urls')),
    path('url-parameters-discussion/', include('the_right_way.url_parameters.discussion_urls')),
    path('detail-view/', include('the_right_way.detail_view.urls')),
    path('detail-view-discussion/', include('the_right_way.detail_view.discussion_urls')),
    path('list-view/', include('the_right_way.list_view.urls')),
    path('list-view-discussion/', include('the_right_way.list_view.discussion_urls')),
    path('delegation/', include('the_right_way.delegation.urls')),
    path('delegation-discussion/', include('the_right_way.delegation.discussion_urls')),
    path('dependency-injection/', include('the_right_way.dependency_injection.urls')),
    path('dependency-injection-discussion/', include('the_right_way.dependency_injection.discussion_urls')),
    path('preconditions/', include('the_right_way.preconditions.urls')),
    path('preconditions-discussion/', include('the_right_way.preconditions.discussion_urls')),
    path('policies/', include('the_right_way.policies.urls')),
]

code/accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    is_premium = models.BooleanField(default=False)
    good_reputation = models.BooleanField(default=False)


class Address(models.Model):
    user = models.ForeignKey(User, related_name='addresses', on_delete=models.CASCADE)
    first_line = models.CharField(max_length=256)
    post_code = models.CharField(max_length=50)
    # etc.
    primary = models.BooleanField(default=False)
    short_name = models.CharField(max_length=50)

    def __str__(self):
        return self.short_name

code/templates/account.html
{% extends "base.html" %}

{% block "content" %}
  <h1>Your account</h1>
  <p>Name: {{ user.full_name }}</p>
  <p>Premium: {{ user.is_premium }}</p>
{% endblock %}

code/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <title>Django Views — The Right Way — {% block "title" %}{% endblock %}</title>
    <link rel="stylesheet" href="https://classless.de/classless.css">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <style>
     .messages {
         background-color: #ffd;
         padding: 0.5em 1em;
     }
    </style>
  </head>
  <body>
    <header>
      {% block "messages" %}
        {% if messages %}
          <div class="messages">
            {% for message in messages %}
              <div{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</div>
            {% endfor %}
          </div>
        {% endif %}
      {% endblock %}
    </header>
    <main>
      {% block "content" %}
      {% endblock %}
    </main>
  </body>
</html>

code/templates/example.html
<html>
  <body>
    <p>Hello, this is an example!</p>
  </body>
</html>

code/templates/hello_world.html
<html>
  <body>
    <p>Hello world!</p>
  </body>
</html>

code/templates/home.html
{% extends "base.html" %}

{% block "content" %}
  This is a home page. The date is {{ today|date:"d M Y" }}.
  {% if special_message %}
    {{ special_message }}
  {% endif %}
{% endblock %}

code/templates/index.html
{% extends "base.html" %}

{% block "title" %}Index{% endblock %}

{% block "content" %}
  <h1>Index of main views</h1>

  <h2>The Pattern</h2>
  <ul>
    <li><a href="{% url "the_pattern:example_name" arg="hello" %}">example</a></li>
    <li><a href="{% url "the_pattern_explanation:hello_world" %}">hello world</a></li>
  </ul>

  <p><a href="{% url "view_source" namespace="the_pattern" %}">[source]</a></p>

  <h2>Context data</h2>
  <ul>
    <li><a href="{% url "context_data:home" %}">home</a></li>
    <li><a href="{% url "context_data:home_2" %}">home 2</a></li>
  </ul>

  <p><a href="{% url "view_source" namespace="context_data" %}">[source]</a></p>

  <h3>Discussion</h2>
  <ul>
    <li><a href="{% url "context_data_discussion:home" %}">home - CBV</a></li>
  </ul>

  <p><a href="{% url "view_source" namespace="context_data_discussion" %}">[source]</a></p>

  <h2>Common context data</h2>
  <ul>
    <li><a href="{% url "common_context_data:checkout_start" %}">checkout start</a></li>
  </ul>

  <p><a href="{% url "view_source" namespace="common_context_data" %}">[source]</a></p>

  <h3>Discussion</h2>
  <ul>
    <li><a href="{% url "common_context_data_discussion:checkout_start" %}">checkout start - CBV</a></li>
  </ul>

  <p><a href="{% url "view_source" namespace="common_context_data_discussion" %}">[source]</a></p>


  <h2>URL parameters</h2>
  <ul>
    <li><a href="{% url "url_parameters:product_detail" slug="test" %}">product detail</a></li>
  </ul>

  <p><a href="{% url "view_source" namespace="url_parameters" %}">[source]</a></p>

  <h3>Discussion</h2>
  <ul>
    <li><a href="{% url "url_parameters_discussion:product_detail_2" name="test" %}">product_detail_2</a></li>
    <li><a href="{% url "url_parameters_discussion:product_detail_3" pk=1 %}">product_detail_3</a></li>
    <li><a href="{% url "url_parameters_discussion:diary_entry" post_date=today %}">diary entry</a></li>
  </ul>

  <p><a href="{% url "view_source" namespace="url_parameters_discussion" %}">[source]</a></p>


  <h2>Detail view</h2>
  <ul>
    <li><a href="{% url "detail_view:product_detail" slug="hanky" %}">product detail</a></li>
  </ul>

  <p><a href="{% url "view_source" namespace="detail_view" %}">[source]</a></p>

  <h3>Discussion</h2>
  <ul>
    <li><a href="{% url "detail_view_discussion:product_detail" slug="hanky" %}">ProductDetailView</a></li>
  </ul>

  <p><a href="{% url "view_source" namespace="detail_view_discussion" %}">[source]</a></p>


  <h2>List view</h2>
  <ul>
    <li><a href="{% url "list_view:product_list_unpaged" %}">product list unpaged</a></li>
    <li><a href="{% url "list_view:product_list" %}">product list paged</a></li>
    <li><a href="{% url "list_view:product_list_refactored" %}">product list refactored</a></li>
  </ul>

  <p><a href="{% url "view_source" namespace="list_view" %}">[source]</a></p>

  <h3>Discussion</h2>
  <ul>
  </ul>

  <p><a href="{% url "view_source" namespace="list_view_discussion" %}">[source]</a></p>


  <h2>Delegation</h2>
  <ul>
    <li><a href="{% url "delegation:special_offer_detail" slug="summer-sale" %}">special offer</a></li>
    <li><a href="{% url "delegation:product_list" %}">product list</a></li>
  </ul>

  <p><a href="{% url "view_source" namespace="delegation" %}">[source]</a></p>

  <h3>Discussion</h2>
  <ul>
    <li><a href="{% url "delegation_discussion:special_offer_detail_fbv" slug="summer-sale" %}">special offer FBV</a></li>
    <li><a href="{% url "delegation_discussion:special_offer_detail_cbv" slug="summer-sale" %}">special offer CBV</a></li>
  </ul>

  <p><a href="{% url "view_source" namespace="delegation_discussion" %}">[source]</a></p>

  <h2>Dependency injection</h2>
  <ul>
    <li><a href="{% url "dependency_injection:special_offer_detail" slug="summer-sale" %}">special offer</a></li>
    <li><a href="{% url "dependency_injection:product_list" %}">product list</a></li>
  </ul>

  <p><a href="{% url "view_source" namespace="dependency_injection" %}">[source]</a></p>

  <h3>Discussion</h2>
  <ul>
    <li><a href="{% url "dependency_injection_discussion:special_offer_detail" slug="summer-sale" %}">special offer CBV</a></li>
    <li><a href="{% url "dependency_injection_discussion:product_list" %}">product list CBV</a></li>
  </ul>

  <p><a href="{% url "view_source" namespace="dependency_injection_discussion" %}">[source]</a></p>


  <h2>Preconditions</h2>
  <ul>
    <li><a href="{% url "preconditions:my_premium_page" %}">premium page</a></li>
  </ul>

  <p><a href="{% url "view_source" namespace="preconditions" %}">[source]</a></p>

  <h3>Discussion</h2>
  <ul>
    <li><a href="{% url "preconditions_discussion:special_1" %}">special_1</a></li>
    <li><a href="{% url "preconditions_discussion:special_2" %}">special_2</a></li>
  </ul>

  <p><a href="{% url "view_source" namespace="preconditions_discussion" %}">[source]</a></p>

  <h2>Policies</h2>
  <h3>django-decorator-include</h3>
  <ul>
    <li><a href="{% url "policies:policies_decorator_include:my_premium_page" %}">premium page</a></li>
  </ul>

  <h3>decorator include with check</h3>
  <ul>
    <li><a href="{% url "policies:policies_decorator_include_check:my_premium_page" %}">premium page</a></li>
    <li><a href="{% url "policies:policies_decorator_include_check:non_premium_page" %}">non premium page</a></li>
  </ul>


{% endblock %}

code/templates/ordinary.html
{% extends "base.html" %}

{% block "content" %}
  <h1>Ordinary page</h1>
  <p>Anyone may view this.</p>

  {% if request.user.is_anonymous %}
    <p>You are anonymous<p>
  {% else %}
      {% if request.user.is_premium %}
        <p>You are a premium user. </p>
      {% else %}
        <p>You are not a premium user. </p>
      {% endif %}
  {% endif %}

{% endblock %}

code/templates/premium_page.html
{% extends "base.html" %}

{% block "content" %}
  <h1>Premium page</h1>

  {% if request.user.is_anonymous or not request.user.is_premium %}
    <p>You are not a premium user. You should not have got here!</p>
  {% else %}
    <p>You are a premium user, welcome!</p>
  {% endif %}
{% endblock %}

code/templates/special.html
{% extends "base.html" %}

{% block "content" %}
  <h1>Special page</h1>
  <p>Yay! you are in...</p>
{% endblock %}